name: vaca-sh-url-shortener
services:
- name: web
  source_dir: /
  github:
    repo: YOUR_GITHUB_USERNAME/vaca-sh-url-shortener
    branch: main
    deploy_on_push: true
  run_command: vendor/bin/heroku-php-apache2 public/
  environment_slug: php
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  health_check:
    http_path: /
  envs:
  - key: APP_NAME
    value: VacaSh
  - key: APP_ENV
    value: production
  - key: APP_KEY
    value: base64:JaRdfC/+ErPWHJJ2B//wGL5duVxDOqzBJZdqvZpX7Cs=
  - key: APP_DEBUG
    value: "false"
  - key: APP_URL
    value: ${APP_URL}
  - key: LOG_CHANNEL
    value: stack
  - key: LOG_LEVEL
    value: error
  - key: SESSION_DRIVER
    value: database
  - key: CACHE_DRIVER
    value: database
  - key: QUEUE_CONNECTION
    value: database
  - key: BROADCAST_DRIVER
    value: log
  - key: SESSION_LIFETIME
    value: "120"
  - key: SESSION_COOKIE_HTTPONLY
    value: "true"
  - key: SESSION_COOKIE_SECURE
    value: "true"
  - key: SESSION_SAME_SITE
    value: lax
  - key: BCRYPT_ROUNDS
    value: "12"
  - key: FILESYSTEM_DISK
    value: local
  - key: MAIL_MAILER
    value: smtp
  - key: MAIL_FROM_ADDRESS
    value: noreply@vaca.sh
  - key: MAIL_FROM_NAME
    value: Vaca.Sh

databases:
- name: db
  engine: MYSQL
  version: "8"
  size: basic
  num_nodes: 1
  production: true 